services:
  api:
    build: .
    container_name: rocket-api
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    environment:
      PYTHONPATH: /app
      WATCHFILES_FORCE_POLLING: "1"

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: rocket-user
      POSTGRES_PASSWORD: R0ck3t4rt1cl35
      POSTGRES_DB: rocket-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pgdata:
